# Generated by Django 4.2.6 on 2023-10-31 02:40

from django.db import migrations, models
import ecological_footprint.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InfosVehiculeFoyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_vehicule",
                    models.CharField(
                        choices=[
                            ("Citadine", "Citadine"),
                            ("Cabriolet", "Cabriolet"),
                            ("Berline", "Berline"),
                            ("SUV / 4x4", "SUV / 4x4"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "energy",
                    models.CharField(
                        choices=[
                            ("Essence", "Essence"),
                            ("Electrique", "Electrique"),
                            ("Gaz", "Gaz"),
                            ("Diesel", "Diesel"),
                            ("Hybride", "Hybride"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mileage",
                    models.IntegerField(
                        validators=[ecological_footprint.models.validate_mileage]
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[ecological_footprint.models.validate_year]
                    ),
                ),
                (
                    "passenger",
                    models.IntegerField(
                        validators=[ecological_footprint.models.validate_passenger]
                    ),
                ),
                ("borrowing_rate", models.FloatField(default=0.0)),
            ],
        ),
    ]
